# Generated by Django 3.0.3 on 2020-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('login', models.CharField(max_length=256, unique=True)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=256, unique=True)),
                ('avatar_url', models.URLField()),
                ('gravatar_id', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
                ('followers_url', models.URLField()),
                ('following_url', models.URLField()),
                ('gists_url', models.URLField()),
                ('starred_url', models.URLField()),
                ('subscriptions_url', models.URLField()),
                ('organizations_url', models.URLField()),
                ('repos_url', models.URLField()),
                ('events_url', models.URLField()),
                ('received_events_url', models.URLField()),
                ('type', models.CharField(max_length=256)),
                ('site_admin', models.BooleanField()),
            ],
        ),
    ]
